/**
 * Visclub SiM - Webbeheerder Bot
 *
 * Deze bot automatiseert verschillende taken:
 * - Website updates
 * - Social media posts (Facebook, YouTube)
 * - Inschrijvingen beheer
 * - Kalender synchronisatie
 * - Email notificaties
 */

const fs = require('fs').promises;
const path = require('path');

// Configuratie
const config = {
    website: {
        dataPath: path.join(__dirname, '../data'),
        publicPath: path.join(__dirname, '../'),
    },
    socialMedia: {
        facebook: {
            enabled: true,
            pageId: 'visclubsim',
            // accessToken: 'YOUR_FB_ACCESS_TOKEN' // Voeg dit toe via environment variables
        },
        youtube: {
            enabled: true,
            channelId: '@visclubsim',
            // apiKey: 'YOUR_YOUTUBE_API_KEY' // Voeg dit toe via environment variables
        }
    },
    email: {
        from: 'SimVisclub@gmail.com',
        // smtp settings hier toevoegen
    },
    notifications: {
        enabled: true,
        daysBeforeCompetition: 7, // Stuur reminder 7 dagen voor wedstrijd
    }
};

class WebbeheerderBot {
    constructor() {
        this.registrations = [];
        this.competitions = [];
        this.init();
    }

    async init() {
        console.log('🤖 Webbeheerder Bot gestart...');
        await this.loadData();
        console.log('✅ Data geladen');
    }

    /**
     * Laad alle data (wedstrijden, inschrijvingen, etc.)
     */
    async loadData() {
        try {
            // Laad inschrijvingen
            const registrationsPath = path.join(config.website.dataPath, 'registrations.json');
            try {
                const data = await fs.readFile(registrationsPath, 'utf8');
                this.registrations = JSON.parse(data);
            } catch (err) {
                console.log('⚠️  Geen registraties gevonden, starting fresh');
                this.registrations = [];
            }

            // Laad wedstrijden (vanuit calendar data in script.js)
            this.competitions = await this.loadCompetitionsFromCalendar();

            console.log(`📊 ${this.registrations.length} inschrijvingen geladen`);
            console.log(`📅 ${this.competitions.length} wedstrijden geladen`);
        } catch (error) {
            console.error('❌ Error loading data:', error);
        }
    }

    /**
     * Laad wedstrijden uit de kalender
     */
    async loadCompetitionsFromCalendar() {
        // Hier zou je de calendar data uit script.js kunnen importeren
        // Voor nu een voorbeeld implementation
        return [
            { date: '2026-03-07', type: 'Vrije Gewone Wedstrijd', participants: [] },
            { date: '2026-03-14', type: 'Vrije Koppelwedstrijd', participants: [] },
            // ... etc
        ];
    }

    /**
     * Voeg nieuwe inschrijving toe
     */
    async addRegistration(competitionDate, participant) {
        const registration = {
            id: Date.now(),
            competitionDate,
            participant,
            registeredAt: new Date().toISOString(),
            status: 'active'
        };

        this.registrations.push(registration);
        await this.saveRegistrations();

        // Update website
        await this.updateWebsiteRegistrations();

        // Stuur bevestigingsmail
        await this.sendConfirmationEmail(registration);

        // Post naar social media (optioneel)
        if (this.shouldPostToSocial(competitionDate)) {
            await this.postToSocialMedia(competitionDate, this.getParticipantCount(competitionDate));
        }

        console.log(`✅ Inschrijving toegevoegd: ${participant.name} voor ${competitionDate}`);

        return registration;
    }

    /**
     * Sla inschrijvingen op
     */
    async saveRegistrations() {
        try {
            const dataPath = path.join(config.website.dataPath, 'registrations.json');
            await fs.mkdir(config.website.dataPath, { recursive: true });
            await fs.writeFile(dataPath, JSON.stringify(this.registrations, null, 2));
        } catch (error) {
            console.error('❌ Error saving registrations:', error);
        }
    }

    /**
     * Update website met nieuwe inschrijvingen
     */
    async updateWebsiteRegistrations() {
        try {
            // Genereer JavaScript bestand met inschrijvingsdata
            const jsContent = `
// Auto-generated by Webbeheerder Bot - ${new Date().toISOString()}
const registrationsData = ${JSON.stringify(this.getRegistrationsByDate(), null, 2)};
`;

            const outputPath = path.join(config.website.publicPath, 'data/registrations-data.js');
            await fs.mkdir(path.dirname(outputPath), { recursive: true });
            await fs.writeFile(outputPath, jsContent);

            console.log('✅ Website bijgewerkt met nieuwe inschrijvingen');
        } catch (error) {
            console.error('❌ Error updating website:', error);
        }
    }

    /**
     * Groepeer inschrijvingen per datum
     */
    getRegistrationsByDate() {
        const grouped = {};
        this.registrations.forEach(reg => {
            if (!grouped[reg.competitionDate]) {
                grouped[reg.competitionDate] = [];
            }
            grouped[reg.competitionDate].push({
                id: reg.id,
                name: reg.participant.name,
                type: reg.participant.type,
                partner: reg.participant.partner || '',
                timestamp: reg.registeredAt
            });
        });
        return grouped;
    }

    /**
     * Tel aantal deelnemers voor een wedstrijd
     */
    getParticipantCount(competitionDate) {
        return this.registrations.filter(r => r.competitionDate === competitionDate).length;
    }

    /**
     * Check of we naar social media moeten posten
     */
    shouldPostToSocial(competitionDate) {
        const count = this.getParticipantCount(competitionDate);
        // Post elke 5 inschrijvingen
        return count > 0 && count % 5 === 0;
    }

    /**
     * Post naar social media
     */
    async postToSocialMedia(competitionDate, participantCount) {
        const message = `🎣 Al ${participantCount} vissers ingeschreven voor de wedstrijd op ${competitionDate}! Schrijf je ook in via onze website! #VisclubSiM #Merksplas`;

        console.log(`📱 Social media post: ${message}`);

        // Facebook post (implementatie met Facebook Graph API)
        if (config.socialMedia.facebook.enabled) {
            await this.postToFacebook(message);
        }

        // YouTube community post (implementatie met YouTube Data API)
        if (config.socialMedia.youtube.enabled) {
            await this.postToYoutube(message);
        }
    }

    /**
     * Post naar Facebook
     */
    async postToFacebook(message) {
        // Implementatie met Facebook Graph API
        console.log('📘 Posting to Facebook...');

        // EXAMPLE (niet geïmplementeerd zonder access token):
        // const response = await fetch(`https://graph.facebook.com/v18.0/${config.socialMedia.facebook.pageId}/feed`, {
        //     method: 'POST',
        //     headers: { 'Content-Type': 'application/json' },
        //     body: JSON.stringify({
        //         message: message,
        //         access_token: config.socialMedia.facebook.accessToken
        //     })
        // });

        console.log('✅ Facebook post scheduled (implementation needed)');
    }

    /**
     * Post naar YouTube
     */
    async postToYoutube(message) {
        console.log('📺 Posting to YouTube...');
        // YouTube community posts require OAuth 2.0
        console.log('✅ YouTube post scheduled (implementation needed)');
    }

    /**
     * Stuur bevestigingsmail
     */
    async sendConfirmationEmail(registration) {
        const { participant, competitionDate } = registration;

        console.log(`📧 Sending confirmation email to ${participant.email}`);

        // Email template
        const emailContent = `
Beste ${participant.firstName} ${participant.lastName},

Je inschrijving voor de wedstrijd op ${competitionDate} is succesvol ontvangen!

Details van je inschrijving:
- Datum: ${competitionDate}
- Type: ${participant.type}
${participant.partner ? `- Koppelgenoot: ${participant.partner}` : ''}
- Inschrijfgeld: ${this.getCompetitionFee(competitionDate)}

Belangrijke informatie:
- Zorg dat je je lidkaart bij je hebt
- Kom op tijd voor de trekking van de visplaatsen
- Neem je afval mee naar huis

Tot dan!

Met sportieve groet,
Visclub SiM
`;

        // EXAMPLE implementatie (vereist SMTP configuratie):
        // await this.sendEmail(participant.email, 'Bevestiging Inschrijving Visclub SiM', emailContent);

        console.log('✅ Confirmation email sent');
    }

    /**
     * Haal inschrijfgeld op voor wedstrijd
     */
    getCompetitionFee(competitionDate) {
        // Lookup in calendar data
        return '€10,00'; // default
    }

    /**
     * Verstuur reminder emails voor aankomende wedstrijden
     */
    async sendUpcomingReminders() {
        console.log('📅 Checking for upcoming competitions...');

        const today = new Date();
        const reminderDate = new Date();
        reminderDate.setDate(today.getDate() + config.notifications.daysBeforeCompetition);

        this.competitions.forEach(async comp => {
            const compDate = new Date(comp.date);
            if (this.isSameDay(compDate, reminderDate)) {
                await this.sendReminderEmails(comp);
            }
        });
    }

    /**
     * Stuur reminder emails voor een specifieke wedstrijd
     */
    async sendReminderEmails(competition) {
        const participants = this.registrations.filter(r => r.competitionDate === competition.date);

        console.log(`📧 Sending ${participants.length} reminder emails for ${competition.date}`);

        for (const reg of participants) {
            const emailContent = `
Beste ${reg.participant.firstName},

Reminder: Over ${config.notifications.daysBeforeCompetition} dagen is de wedstrijd!

Datum: ${competition.date}
Type: ${competition.type}

Vergeet niet:
- Je lidkaart mee te nemen
- Op tijd aanwezig te zijn
- Je vismateriaal te controleren

Tot dan!

Visclub SiM
`;
            // await this.sendEmail(reg.participant.email, 'Reminder: Wedstrijd aanstaande', emailContent);
        }

        console.log('✅ Reminder emails sent');
    }

    /**
     * Check of twee datums dezelfde dag zijn
     */
    isSameDay(date1, date2) {
        return date1.getDate() === date2.getDate() &&
               date1.getMonth() === date2.getMonth() &&
               date1.getFullYear() === date2.getFullYear();
    }

    /**
     * Genereer rapport van alle inschrijvingen
     */
    async generateReport() {
        console.log('\n📊 INSCHRIJVINGEN RAPPORT\n');
        console.log(`Totaal inschrijvingen: ${this.registrations.length}`);

        const byDate = this.getRegistrationsByDate();
        Object.keys(byDate).forEach(date => {
            console.log(`\n${date}: ${byDate[date].length} deelnemers`);
            byDate[date].forEach((p, i) => {
                console.log(`  ${i + 1}. ${p.name} (${p.type})`);
            });
        });
    }

    /**
     * Start automatische taken (cron jobs)
     */
    startAutomation() {
        console.log('🚀 Starting automation tasks...');

        // Check elke dag om 9:00 voor aankomende wedstrijden
        setInterval(() => {
            const now = new Date();
            if (now.getHours() === 9 && now.getMinutes() === 0) {
                this.sendUpcomingReminders();
            }
        }, 60000); // Check elke minuut

        // Sync data elk uur
        setInterval(() => {
            this.loadData();
        }, 3600000); // 1 uur

        console.log('✅ Automation tasks started');
    }
}

// Export de bot
module.exports = WebbeheerderBot;

// Als dit script direct wordt uitgevoerd
if (require.main === module) {
    const bot = new WebbeheerderBot();

    // Start automation
    bot.startAutomation();

    // Example: Voeg test inschrijving toe
    // bot.addRegistration('2026-03-07', {
    //     firstName: 'Test',
    //     lastName: 'Gebruiker',
    //     email: 'test@example.com',
    //     type: 'solo',
    //     partner: null
    // });

    // Generate rapport
    setTimeout(() => {
        bot.generateReport();
    }, 2000);
}
